### ISSUE TITLE
How to get back indent line when using this theme?

### ISSUE THREAD

**Issue by vivekkumar27june88** [clintonrost/theme-firefox-devtools#1]
How to get back indent guide when using this theme?

**Comment by clintonrost** [comment]
Vivek, I will find a solution for you in the next couple of days.  I need to set aside some time to make a helpful response.

**Comment by clintonrost** [comment]
Vivek, the easiest way to add back the indent guide is to modify your user settings with the following: 

```
"workbench.colorCustomizations": {
	"editorIndentGuide.background": "#42495460",
	"editorIndentGuide.activeBackground": "#204e8a"
},
```
Of course, you can change the color values to whatever you would like, these are values that exist in other places in the theme.

Documentation:

- [Workspace Settings](https://code.visualstudio.com/docs/getstarted/settings)
- [Indent Guides](https://code.visualstudio.com/updates/v1_23#_highlighted-indent-guides)


I'm considering how I'm going to add this option to the theme for future versions.
